services:
  - type: web
    name: party-pilot
    env: node
    buildCommand: |
      npm install
      npm run install:frontend
      npm run install:backend
      npm run build
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false